avalonmediasystem/react-structural-metadata-editor

src/services/StructuralMetadataUtils.js
src/services/WaveformDataUtils.js

There can be overlapping timespans set in legacy editor in Avalon. When trying to edit these within SME, the application crashes. This is fixed in this PR.

Edit overlapping timespans

---

src/components/ListItem.js
src/containers/WaveformContainer.js

This PR fixes 2 bugs;
1. If a user edits a timespan while DnD is enabled for that particular timespan, the inline edit form is displayed while the DnD is enabled. Even though this doesn't break the application (I couldn't find a way to break it, but maybe possible),  it doesn't look good. @adamjarling If you think this should stay as the way it is, we can revert this :+1: 
2. If a user deletes a timespan while DnD is enabled for that timespan, that particular item gets deleted. But the drop-zones are not removed.
3. When `waveform.json` is not fetched and a warning is emitted, the structure remains editable. If a user clicks on an edit icon for a timespan the app breaks since that action is bound to the Peaks instance, which is created upon successful retrieval of the `waveform.json`.

Small bug fixes 

---

dist/components/ButtonSection.js
dist/components/ListItem.js
dist/components/ListItemControls.js
dist/containers/WaveformContainer.js
dist/reducers/forms.js
src/components/ButtonSection.js
src/components/ListItem.js
src/components/ListItemControls.js
src/containers/WaveformContainer.js
src/reducers/forms.js

This fixes an issue mentioned in avalonmediasystem/avalon#3334
> Only one editing mode should be available to be used at one time. The two modes are rearranging (dra and drop) and editing. If one is active, the other should be disabled.
Additionally, changed the code passed in the redux store action `handleEditingTimespans` to turn on and off disabling other editing actions when one action is performed. Previously it was;
```
if(code === 0) {
set editingDisabled: true;
}
```
Now, using 1 for boolean value `true` according to common practice;
```
if (code === 1) {
set editingDisabled: true;
}
```
There is no logic changes in the application regarding this, but the values passed to the function.

Disable other editing actions when DnD is turned on for an item

---

dist/components/TimespanForm.js
dist/services/StructuralMetadataUtils.js
dist/services/StructuralMetadataUtils.test.js
src/components/TimespanForm.js
src/services/StructuralMetadataUtils.js
src/services/StructuralMetadataUtils.test.js

This fixes the following issues mentioned in avalonmediasystem/avalon#3334;
> The “Child Of” drop-down doesn’t show all of the expected values. For example, it sometimes doesn’t show the top-most heading , or the last heading, even when the timespan is valid to be placed there.

Fix missing headings when adding new timespans

---

src/App.css
src/components/Slider.js

Intended behavior: when slider is dragged until volume is 0 and then clicked on the volume icon, the volume should set to the previous value (the volume the slider was at before dragging it).
This did not happen as the previous volume was constantly set when slider was dragged, which is removed in this PR.

Bug fix in volume slider

---

src/components/TimespanForm.js
src/components/__tests__/TimespanForm.test.js
src/services/StructuralMetadataUtils.js
src/services/testing-helpers.js

Updated the `renderWithRedux` utility function to accommodate re-rendering of a component to reflect changes to props, which affects the behavior of the component

Add tests for TimespanForm component

---

dist/actions/peaks-instance.js
dist/containers/WaveformContainer.js
src/actions/peaks-instance.js
src/containers/WaveformContainer.js

Add missing `duration` property passed into `buildSMUI` function to fill in missing end property within structure fetched from server. The state variable `streamLength` in `WaveformContainer` was removed when merging the file.

Fix missing file endtime passed in to build SM-UI

---

__mocks__/peaks.js
dist/components/Slider.js
dist/components/__tests__/ButtonSection.test.js
dist/components/__tests__/ListItem.test.js
dist/components/__tests__/ListItemEditForm.test.js
dist/components/__tests__/TimespanForm.test.js
dist/components/__tests__/TimespanInlineForm.test.js
dist/data/mock-response-structure.json
dist/reducers/peaks-instance.js
dist/reducers/sm-data.js
dist/services/StructuralMetadataUtils.js
dist/services/StructuralMetadataUtils.test.js
dist/services/WaveformDataUtils.js
dist/services/WaveformDataUtils.test.js
dist/services/testing-helpers.js
src/components/__tests__/ButtonSection.test.js
src/components/__tests__/ListItem.test.js
src/components/__tests__/ListItemEditForm.test.js
src/components/__tests__/TimespanForm.test.js
src/components/__tests__/TimespanInlineForm.test.js
src/data/mock-response-structure.json
src/services/StructuralMetadataUtils.js
src/services/StructuralMetadataUtils.test.js
src/services/WaveformDataUtils.js
src/services/WaveformDataUtils.test.js
src/services/testing-helpers.js

Fixes #68.
This PR naively updates all tests to use thousandths of seconds and fixes a few functions so the tests pass.  I did a quick manual test of the standalone SME and everything looked good.  
Peaks.js is only using hundredths for the playhead and drag handles but I didn't know how to override a peaks function.  It looks like we just need to add a zero here: https://github.com/bbc/peaks.js/blob/9f37a10746366142da3bd5c74083f2251b3c0c7f/src/main/waveform/waveform.utils.js#L45

Always operate in thousandths of a second

---

dist/services/StructuralMetadataUtils.js
dist/services/__test__/StructuralMetadataUtils.test.js
dist/services/testing-helpers.js
src/services/StructuralMetadataUtils.js
src/services/__test__/StructuralMetadataUtils.test.js
src/services/testing-helpers.js

With the work in the PR, SME parses timecodes in the following formats;
* `mm.ss`(eg: `5.30` -> 5 minutes and 30 seconds)
* `hh:mm:ss`(eg: `00:02:42` -> 0 hours 2 minutes and 42 seconds)
* `mm`(eg: `5` -> 5 minutes)
Along with,
* `hh:mm:ss.ms`(eg: `00:23:43.23` -> 0 hours 23 minutes 43 seconds and 23 milliseconds)

Fix parsing different time formats from back-end correctly

---

dist/App.css
dist/components/ButtonSection.js
src/App.css
src/components/ButtonSection.js

The user can edit and delete the existing structure while the derivative is fetched. And then save it back to the server. 
This PR contains a fix to block the UI while the media is fetched.

Block UI when loading

---

dist/App.css
dist/App.js
src/App.css
src/App.js

When structural metadata editor is opened in Avalon, for some screen widths the content overflows the modal.
This happens because all the components within SME are enclosed in a `<div>` with `class="container"`, which is used in Bootstrap for responsive design. When SME is added to Avalon the Bootstrap CSS in Avalon gets applied here causing the overflow.
Content in the modal do not overflow.

Change CSS class to avoid external style getting applied

---

dist/services/StructuralMetadataUtils.js
dist/services/WaveformDataUtils.js
dist/services/__test__/StructuralMetadataUtils.test.js
dist/services/__test__/WaveformDataUtils.test.js
dist/services/testing-helpers.js
package.json
src/services/StructuralMetadataUtils.js
src/services/WaveformDataUtils.js
src/services/__test__/StructuralMetadataUtils.test.js
src/services/__test__/WaveformDataUtils.test.js
src/services/testing-helpers.js
yarn.lock

Changes in this PR:
1. Support for hh:mm:ss(.ss), mm:ss(.ss), and ss(.ss) time formats
2. Removed moment.js dependency
3. Quick fix for timespan validation when dragging handles in waveform

Add support for mm:ss.ms time format

---

package.json
yarn.lock

Change versions of `mkdirp` and `istanbul-reports` to upgrade `minimist` package's version to a higher version.

Bump minimist package version > 0.2.1

---

dist/actions/forms.js
package.json
src/actions/forms.js
yarn.lock

The warning message flashes on load, because HLS error handling code in SME catches a uncaught error from HLS.js; `ReferenceError: o is not defined`
The respective issue for this in HLS repository is [here](https://github.com/video-dev/hls.js/issues/2435).
The HLS error type of this is `OTHER_ERROR`, therefore I have excluded errors with this type in the HLS error handling block in SME code. Even though this is not the ideal solution, we can keep it until HLS fixes this issue from their end.
This doesn't happen in the standalone application, because I think this reference issue is introduced when webpack builds HLS.

Fix flashing error message on load

---

dist/services/StructuralMetadataUtils.js
dist/services/__test__/StructuralMetadataUtils.test.js
src/services/StructuralMetadataUtils.js
src/services/__test__/StructuralMetadataUtils.test.js
src/services/testing-helpers.js

When adding a new timespan the parents suggestion list in the timespan form doesn't include childless headings comes after the new timespan. And this PR fixes that bug.

Fix bug in parent suggestions when adding a new timespan

---

yarn.lock

This PR fixes 2 high-severity security alerts for packages `node-forge` and `serialize-javascript` packages.

Fix high-severity security alerts

---

package.json
yarn.lock

`terser` is a dependency injected via `webpack`. Therefore upgrading `webpack` and `html-webpack-plugin` (needed to be upgraded with webpack) to fix the security vulnerability resulted by `terser v4.8.0`.

Upgrade webpack to fix security alert for terser package

---

dist/actions/peaks-instance.js
src/actions/peaks-instance.js

For shorter media files, the waveform zoom view created with default zoom levels shows empty space at the end when zooming out. 
This PR adds different zoom levels to be used for shorter media files so that, the empty space at the end is not displayed.
Before:
After:

Fix waveform zoom levels for shorter media files

---

dist/actions/forms.js
dist/components/Waveform.js
src/actions/forms.js
src/components/Waveform.js

Wait for HLS.js to finish re-trying to fetch stream when a 403 error occurs, without removing the loading spinner blocking the UI.

Fix 403 error in fetching stream files

---

src/containers/StructureOutputContainer.js

In SME `Save Structure` button is supposed to be disabled when editing the structure. This was broken since the prop that was expected to be enabling/disabling the button was removed in the `SturcutreOutputContainer` component. This PR fixes this bug.

Disable save structure button when editing structure

---

demo/src/app.js
demo/src/index.html
package.json
public/dev/manifest.json
public/prod/manifest.json
src/App.js
src/components/HeadingForm.js
src/components/ListItemControls.js
src/components/TimespanForm.js
src/components/TimespanInlineForm.js
src/components/Waveform.js
src/containers/StructureOutputContainer.js
src/containers/WaveformContainer.js
yarn.lock

The latest `react-bootstrap` version no longer bundles all Bootstrap 5 classes, so SME now requires `bootstrap` to be installed as a separate dependency. Previously, `react-bootstrap` included these classes, removing the need for a standalone `bootstrap` installation.
Currently, SME is installing the `bootstrap` JavaScript library as a direct dependency and importing its CSS at the root level of our exported component. This approach creates several issues for consuming applications:
- Redundant Dependencies: When a consuming application (like Avalon) installs our component, it also installs `bootstrap`. This is redundant if the consuming application already uses its own Bootstrap installation (e.g., `bootstrap` gem).
- Styling Conflicts and Overrides: Importing Bootstrap's CSS directly …

Move Bootstrap to peerDeps, cleanup Bootstrap 4 refs and classes
